# Generated by Django 3.0.7 on 2022-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qr_code', models.TextField()),
                ('hash_id', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField()),
                ('data_utilizacao', models.DateTimeField(null=True)),
            ],
        ),
    ]
