# Generated by Django 3.2 on 2022-05-10 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupom',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='data_utilizacao',
        ),
        migrations.AddField(
            model_name='cupom',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupom',
            name='date_use',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
