# Generated by Django 3.2 on 2022-05-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0002_auto_20220510_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupom',
            new_name='Teste',
        ),
    ]
