# Generated by Django 3.2 on 2022-05-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0003_rename_cupom_teste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teste',
            new_name='Record',
        ),
    ]
