# Generated by Django 3.2 on 2022-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0004_rename_teste_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_use',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
