# Generated by Django 3.2 on 2022-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0005_auto_20220511_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
